# =============================================================================
# DiskIOStress - Linux storage data integrity stress test
# =============================================================================

CC       := gcc
CFLAGS   := -Wall -Wextra -O2 -Iinclude -MMD -MP
LDLIBS   := -lpthread -luring

BUILD    := build
OBJDIR   := $(BUILD)/obj
TESTOBJ  := $(BUILD)/testobj
BIN      := $(BUILD)/DiskIOStress
TESTBIN  := $(BUILD)/test_runner

SRC      := $(wildcard src/*.c)
OBJ      := $(patsubst src/%.c,$(OBJDIR)/%.o,$(SRC))

# Sources to include in test build (everything except main.c).
SRC_NOMAIN := $(filter-out src/main.c,$(SRC))
LIBOBJ     := $(patsubst src/%.c,$(TESTOBJ)/%.o,$(SRC_NOMAIN))

TEST_SRC   := $(wildcard tests/test_*.c)
TEST_OBJ   := $(patsubst tests/%.c,$(TESTOBJ)/%.o,$(TEST_SRC))
UNITY_OBJ  := $(TESTOBJ)/unity.o

# Test runner is auto-generated by Unity helpers; we ship a small main.
TEST_MAIN_OBJ := $(TESTOBJ)/test_main.o

TEST_CFLAGS := $(CFLAGS) -Itests/unity -DUNITY_OUTPUT_COLOR

.PHONY: all clean test help

all: $(BIN)

# Compile main app
$(BIN): $(OBJ) | $(BUILD)
	$(CC) -o $@ $^ $(LDLIBS)

$(OBJDIR)/%.o: src/%.c | $(OBJDIR)
	$(CC) $(CFLAGS) -c -o $@ $<

# Test runner
test: $(TESTBIN)
	@echo "--- Running tests ---"
	@$(TESTBIN)

$(TESTBIN): $(LIBOBJ) $(UNITY_OBJ) $(TEST_OBJ) $(TEST_MAIN_OBJ) | $(BUILD)
	$(CC) -o $@ $^ $(LDLIBS)

$(TESTOBJ)/%.o: src/%.c | $(TESTOBJ)
	$(CC) $(TEST_CFLAGS) -c -o $@ $<

$(TESTOBJ)/%.o: tests/%.c | $(TESTOBJ)
	$(CC) $(TEST_CFLAGS) -c -o $@ $<

$(UNITY_OBJ): tests/unity/unity.c | $(TESTOBJ)
	$(CC) $(TEST_CFLAGS) -c -o $@ $<

$(BUILD) $(OBJDIR) $(TESTOBJ):
	@mkdir -p $@

# Auto-generated header dependencies (-MMD), so editing a .h rebuilds dependents.
-include $(OBJ:.o=.d)
-include $(LIBOBJ:.o=.d)
-include $(TEST_OBJ:.o=.d)
-include $(TEST_MAIN_OBJ:.o=.d)

clean:
	rm -rf $(BUILD) *.dat log.txt rtc.log

help:
	@echo "Targets:"
	@echo "  make        - build $(BIN)"
	@echo "  make test   - build & run unit tests"
	@echo "  make clean  - remove build/ and generated logs"
